### ISSUE TITLE
프로젝트 역할분담 

### ISSUE THREAD

**Issue by zcxz1432** [zcxz1432/simple_game_proj#1]
각자 역할을 분배 
1.  게임 전체적인 레이아웃(프레임, 배경)짜기 & 이미지 검색 
2.  게임 창 만들기(주인공 캐릭터, 적 캐릭터 생성, 캐릭터 hp바 생성)
3.  게임 버튼 및 버튼 이미지 만들기(공격, 방어, 휴식, 은신, 종료)
4.  텍스트 실행창 만들기(캐릭터들의 hp와 버튼 결과 텍스트화)
5.  게임 실행 배경음악 삽입

이 외에 기능 추가 할 것들은 각자 ISSUE 게시판에 올리기

**Comment by zcxz1432** [comment]
+) 게임 시작화면 생성(구성 : 게임 제목, start 버튼, 게임 설명 버튼)
+) 게임 설명 화면 생성
+) 게임 종료 화면 & 버튼 생성

**Comment by xxoha** [comment]
나는 3번 할게~

**Comment by aka3018** [comment]
그럼 내가 2번, 5번 할게~~

**Comment by zcxz1432** [comment]
그러면 나는 1번이랑 4번 할겡 !
