### ISSUE TITLE
버튼 이미지 투표

### ISSUE THREAD

**Issue by zcxz1432** [zcxz1432/simple_game_proj#3]
댓글에 
sword - 
shield - 
heal -
hide -
out -
복사해서 번호로 적어쥬세여

sword 

![sword 3](https://user-images.githubusercontent.com/56594496/83166550-0ca4cc00-a14a-11ea-9d9e-950faa4d0600.JPG)
![sword1](https://user-images.githubusercontent.com/56594496/83166553-0dd5f900-a14a-11ea-9368-2efff81899b8.JPG)
![sword2](https://user-images.githubusercontent.com/56594496/83166555-0dd5f900-a14a-11ea-9f4a-797ddb57f43c.JPG)

sheild

![shiled2](https://user-images.githubusercontent.com/56594496/83166609-2514e680-a14a-11ea-8461-d729cc87db7c.JPG)
![shield](https://user-images.githubusercontent.com/56594496/83166612-25ad7d00-a14a-11ea-9113-691b2c1bcdd0.png)
![shield](https://user-images.githubusercontent.com/56594496/83166613-26461380-a14a-11ea-949b-91aaf4e68d9c.JPG)

heal (pill)

![heal 2](https://user-images.githubusercontent.com/56594496/83166645-33630280-a14a-11ea-8af0-6bb4eda3a7c2.JPG)
![pill](https://user-images.githubusercontent.com/56594496/83166649-33fb9900-a14a-11ea-8b12-ce77f7b0b564.png)
![heal 1](https://user-images.githubusercontent.com/56594496/83166655-34942f80-a14a-11ea-835d-d32d0136ff99.JPG)

hide

![hide 2](https://user-images.githubusercontent.com/56594496/83166671-39f17a00-a14a-11ea-8aa8-034bf00e3c96.JPG)
![hide 1](https://user-images.githubusercontent.com/56594496/83166673-3b22a700-a14a-11ea-91bc-e91afe71425b.JPG)

out

![out1](https://user-images.githubusercontent.com/56594496/83166697-4249b500-a14a-11ea-801d-20d4352b31e4.JPG)

![out 2](https://user-images.githubusercontent.com/56594496/83166695-41188800-a14a-11ea-921c-b86f65a0ced0.JPG)

sword 1
https://www.flaticon.com/free-icon/sword_2466937

sword 2
https://www.flaticon.com/free-icon/dagger_2917375

sword 3
https://www.flaticon.com/free-icon/sword_2074797

shield 
https://www.flaticon.com/free-icon/shield_599184?term=defense&page=2&position=41

shield 1
https://www.flaticon.com/free-icon/safety_2928915

shield 2
https://www.flaticon.com/free-icon/secure-shield_388500

heal 1
https://www.flaticon.com/free-icon/pills_975823

heal 2
https://www.flaticon.com/free-icon/pills_822092

pill 
https://www.flaticon.com/free-icon/pill_2634087?term=Healing&page=2&position=92

hide 1
https://www.flaticon.com/free-icon/blind_2852458?term=hide&page=1&position=39

hide 2
https://www.flaticon.com/free-icon/close-eyes_2764424

out 1
https://www.flaticon.com/free-icon/logout_1828407
out 2
https://www.flaticon.com/free-icon/x-mark_1617543

**Comment by aka3018** [comment]
sword -3
shield -3
heal -1
hide -2
out -1

근데 은신은 1번도 괜찮은듯

**Comment by xxoha** [comment]
sword -1
shield -3
heal -1
hide -1
out -1

**Comment by zcxz1432** [comment]
sword - 3
shield - 3
heal - 1 
hide - 
out -
근데 난 hide랑 out 상관 없을 거 같앵

**Comment by zcxz1432** [comment]
그럼 sword 3
shield 3
heal 1
hide 1
out 1
으로 하는걸로 할게용
