### ISSUE TITLE
배경음악 투표 

### ISSUE THREAD

**Issue by aka3018** [zcxz1432/simple_game_proj#5]
1. https://youtu.be/kALNXYwgYP0

2. https://youtu.be/NP0yo7UWY_0

3. https://youtu.be/a9vRItV9TZc

배경음악 투표 해주세여
 1번에는 여러 개 있는데 제일 첫번째로 나오는 음악이야

**Comment by xxoha** [comment]
3번~~~~~~~

**Comment by zcxz1432** [comment]
3번은 어떠신가욤

**Comment by aka3018** [comment]
그럼 3번으로 할게요~~
