### ISSUE TITLE
버튼 이벤트 처리 역할 

### ISSUE THREAD

**Issue by aka3018** [zcxz1432/simple_game_proj#6]
1.공격
2.방어
3.회복
4.은신 
중에 이벤트 처리 하고 싶은거 골라서 의견 남겨주세여~ 
1,3 은 hp 처리하고 3은 방패그림 띄우고 4는 캐릭터 사라지게 하면 될거같음!

**Comment by zcxz1432** [comment]
23 할게 ~

**Comment by xxoha** [comment]
1번할게유

**Comment by aka3018** [comment]
그럼 내가 4번 할게
