### ISSUE TITLE
공격 이벤트 처리 버그 

### ISSUE THREAD

**Issue by aka3018** [zcxz1432/simple_game_proj#7]
은신 버튼 클릭 후 공격 버튼을 누르면 player 이미지가 뜨지 않는 
버그가 발생하여 수정했습니다.
1b5da132f3b6a28fd1a3b506185cebdb1af6942d
@zcxz1432 , @xxoha
확인해주세요 ~

**Comment by zcxz1432** [comment]
오 확인 못했었는데 고마워유 ~

**Comment by xxoha** [comment]
확인했어융
