### ISSUE TITLE
오류 처리 

### ISSUE THREAD

**Issue by zcxz1432** [zcxz1432/simple_game_proj#8]

**Comment by zcxz1432** [comment]
공격 버튼 클릭 후 치유 클릭시 hp바 오류 수정 완료 
211fb80391899861f789d8b0b6c9ce61c07a7bf7

**Comment by xxoha** [comment]
은신 후 공격 버튼 클릭 시 용사 두사 둘다 피 줄었는데 두사 피만 줄어들도록 수정 완료
3f2a9f9a636496311e8a91bf563a5d4e7fde5ca4

**Comment by aka3018** [comment]
은신 버튼 클릭 후 공격 버튼을 누르면 player 이미지가 뜨지 않는 오류 수정 완료 
1b5da13

**Comment by zcxz1432** [comment]
용사 레벨업시 두사 hp 회복 되지 않는 오류 수정 
f46d56686f9712eb56d2ee0cefe2ce824d84b024
